### PR TITLE
feat(XbyK Update): update XbyK libraries to version 30.0.0. Update dancing goat to the latest version.

### PR DESCRIPTION
**Pull request by bkapustik**
# Motivation

* Updates integration XbyK references to version 30.0.0
* Updates .NET reference to version 8
* Updates Dancing Goat example to use the latest api changes
* Returns back search view example

### CODE REVIEW

**Comment by michalJakubis** [comment]
Do not forget to update version of XbK npm packages as well https://github.com/Kentico/xperience-by-kentico-lucene/blob/333c048188dbe95e4bfbd2ed17cd336eacfc3da7/src/Kentico.Xperience.Lucene.Admin/Client/package.json#L16

**Comment by Rumec** [comment]
Also when looking at GH actions there are warnings about the use of obsolete API, fix this:

image

**Review by Rumec — CHANGES_REQUESTED** [review]
Changes requested - check comments at PR.

**Comment by Rumec** [comment]
> Do not forget to update version of XbK npm packages as well.
> 
> https://github.com/Kentico/xperience-by-kentico-lucene/blob/333c048188dbe95e4bfbd2ed17cd336eacfc3da7/src/Kentico.Xperience.Lucene.Admin/Client/package.json#L16
> 
> @Rumec This is constantly forgotten during updates. We should consider implementing some kind of automatic check.

@bkapustik fix this

**Review by Rumec — APPROVED** [review]
Review OK

**Pull request merged**
